window.LAB_PAPERS_DATA = {
  "paperFiles": [
    "TIFS2023SAGE",
    "AAAI2023Purifier",
    "ESE2022SmartFast",
    "TDSC2023ERNN",
    "TDSC2023I2RNN",
    "TMC2023CMD",
    "TSE2023VulHunter",
    "INFOCOM2024RIDS",
    "CompSecurity2024DDoSFamily",
    "TDSC2024MLTrafficShaping",
    "ACNS2024DDoSMiner",
    "WWW2024Trident",
    "TON2024FOSS",
    "TCAD2024TPEDet",
    "ICWS2024Moirai",
    "MM2024Minerva",
    "TCAD2024QuST",
    "SECON2024P2PBotnetDetection",
    "CompNet2024metaNet",
    "CSCWD2024AlertCrossVerification",
    "KDD2025TimeWaveletFusion",
    "DATE2025MoECalibration",
    "INFOCOM2025Fortuna",
    "DASFAA2025CyberLLM",
    "JSAC2025VerifyAllTraffic",
    "FSE2025CAShift",
    "IJCAI2025QuantumServerlessDeployment",
    "MM2025StealthyAE",
    "TON2025TNT",
    "TON2025SOFA",
    "TIFS2025CGIFuzz",
    "ASE2025AutoFid",
    "TIFS2025QuantumCloudFingerprinting",
    "AAAI2026AdaptiveFidelityEstimation",
    "AAAI2026RelationalVerification",
    "KDD2026VQFlow",
    "KDD2026QuaMap",
    "NDSS2026Chimera"
  ],
  "ccfFields": [
    "计算机体系结构/并行与分布计算/存储系统",
    "计算机网络",
    "网络与信息安全",
    "软件工程/系统软件/程序设计语言",
    "数据库/数据挖掘/内容检索",
    "计算机科学理论",
    "计算机图形学与多媒体",
    "人工智能",
    "人机交互与普适计算",
    "交叉/综合/新兴"
  ],
  "researchDirections": [
    "网络与算网融合",
    "隐私计算",
    "大模型推理与训练",
    "量子智能",
    "医学智能",
    "脑机与生成式智能",
    "AI for Science"
  ],
  "ccfFieldAbbr": {
    "计算机体系结构/并行与分布计算/存储系统": "体系结构",
    "计算机网络": "计算机网络",
    "网络与信息安全": "网络安全",
    "软件工程/系统软件/程序设计语言": "软件工程",
    "数据库/数据挖掘/内容检索": "数据库/挖掘",
    "计算机科学理论": "CS理论",
    "计算机图形学与多媒体": "图形学/多媒体",
    "人工智能": "人工智能",
    "人机交互与普适计算": "人机交互",
    "交叉/综合/新兴": "交叉/新兴"
  }
};
